name: Test Workspaces

on: [push]

jobs:
  test:
    name: Test Zerkel
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Test Everything
        run: npm run test-zerkel
